In [561]:
import sklearn
import pandas as pd
import matplotlib.pyplot as plt 
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn import metrics
import sklearn.preprocessing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn import preprocessing

In [562]:
df1 = pd.read_csv("LoanStats3c_securev1.csv", skiprows=1)


In [563]:
df2 = df1*1
print(df2.columns)
df2['settlement_amount'].value_counts()

Index(['id', 'member_id', 'loan_amnt', 'funded_amnt', 'funded_amnt_inv',
       'term', 'int_rate', 'installment', 'grade', 'sub_grade',
       ...
       'orig_projected_additional_accrued_interest',
       'hardship_payoff_balance_amount', 'hardship_last_payment_amount',
       'debt_settlement_flag', 'debt_settlement_flag_date',
       'settlement_status', 'settlement_date', 'settlement_amount',
       'settlement_percentage', 'settlement_term'],
      dtype='object', length=150)


5000.00     17
3000.00     15
4500.00     11
5500.00     11
7000.00     10
10000.00     9
9000.00      8
6000.00      8
12000.00     8
2500.00      8
1500.00      8
3500.00      7
8000.00      7
6500.00      7
4000.00      6
7500.00      6
2000.00      5
4800.00      5
6600.00      5
3700.00      5
2630.00      4
1650.00      4
3300.00      4
12500.00     4
800.00       4
2300.00      4
20000.00     4
2633.00      4
2800.00      4
1300.00      4
            ..
8320.60      1
1878.73      1
3797.92      1
2879.43      1
4036.55      1
586.00       1
5402.00      1
10213.06     1
991.00       1
6239.05      1
9824.00      1
4386.29      1
3750.00      1
1040.80      1
7443.00      1
2750.79      1
3891.93      1
5394.00      1
3101.00      1
3915.81      1
7341.07      1
1860.00      1
8369.90      1
1152.06      1
6716.01      1
3179.03      1
8096.15      1
8373.65      1
3023.55      1
3072.00      1
Name: settlement_amount, Length: 3996, dtype: int64

In [564]:

"""
df2['loan_status'].value_counts()
df2['loan_amnt'].value_counts()
df2['mths_since_recent_bc'].value_counts()
df2['acc_open_past_24mths'].value_counts()

"""
loan_status_map = {'Fully Paid': 0, 'Charged Off': 1}
df2['loan_status'] = df2['loan_status'].map(loan_status_map)
df2['int_rate'] = df2['int_rate'].str.replace("%","")
grade_map = {'A':0, 'B':1, 'C':2, 'D':3, 'E':4, 'F':5}
df2['grade'] = df2['grade'].map(grade_map)
xy = df2[['loan_amnt', 'mths_since_recent_bc','loan_status', 'grade','funded_amnt','int_rate','installment','annual_inc']].dropna()
xy.dropna()
xy


loan_amnt  mths_since_recent_bc  loan_status  grade  funded_amnt  \
0         10400.0                   5.0          1.0    0.0      10400.0   
1         15000.0                  47.0          0.0    2.0      15000.0   
2          9600.0                  24.0          0.0    2.0       9600.0   
3         12800.0                  21.0          0.0    3.0      12800.0   
4         21425.0                   7.0          0.0    3.0      21425.0   
5          7650.0                  17.0          1.0    2.0       7650.0   
6         23325.0                  23.0          1.0    2.0      23325.0   
7         12975.0                   6.0          1.0    3.0      12975.0   
8         17000.0                  27.0          0.0    2.0      17000.0   
9          2500.0                  24.0          0.0    1.0       2500.0   
10         5250.0                  16.0          0.0    1.0       5250.0   
11        16000.0                  80.0          0.0    1.0      16000.0   
12        10000.0                  42.0          1.0    1.0      10000.0   
14         6000.0                  15.0          0.0    1.0       6000.0   
15         2000.0                   3.0          0.0    3.0       2000.0   
16         2000.0                   8.0          0.0    2.0       2000.0   
17         3000.0                  27.0          0.0    1.0       3000.0   
18        28000.0                   1.0          0.0    1.0      28000.0   
20        18000.0                   8.0          0.0    1.0      18000.0   
21        14000.0                  35.0          0.0    1.0      14000.0   
22         4000.0                  33.0          0.0    3.0       4000.0   
23         2000.0                  27.0          0.0    2.0       2000.0   
24        18450.0                  17.0          1.0    2.0      18450.0   
25        15000.0                  20.0          0.0    4.0      15000.0   
27         6000.0                   4.0          0.0    2.0       6000.0   
28         2000.0                  18.0          0.0    2.0       2000.0   
29         7200.0                  10.0          0.0    2.0       7200.0   
30        10800.0                  30.0          0.0    1.0      10800.0   
31         1000.0                 102.0          0.0    2.0       1000.0   
32         5000.0                  15.0          0.0    2.0       5000.0   
...           ...                   ...          ...    ...          ...   
235599    35000.0                   1.0          0.0    3.0      35000.0   
235600    15000.0                  19.0          1.0    3.0      15000.0   
235601    12800.0                  12.0          0.0    1.0      12800.0   
235602    24000.0                   2.0          0.0    4.0      24000.0   
235603    18000.0                  16.0          0.0    2.0      18000.0   
235604     7000.0                   3.0          0.0    1.0       7000.0   
235605    14400.0                  67.0          0.0    1.0      14400.0   
235606    14000.0                   8.0          0.0    2.0      14000.0   
235607    24000.0                   1.0          0.0    2.0      24000.0   
235608    15250.0                  11.0          0.0    3.0      15250.0   
235609    32000.0                  18.0          0.0    0.0      32000.0   
235610    12000.0                   4.0          0.0    0.0      12000.0   
235611    10000.0                  95.0          0.0    1.0      10000.0   
235612    10000.0                   1.0          0.0    0.0      10000.0   
235613     5000.0                  40.0          0.0    4.0       5000.0   
235614    12000.0                  40.0          0.0    2.0      12000.0   
235615    13250.0                  25.0          0.0    4.0      13250.0   
235616    12000.0                   2.0          0.0    4.0      12000.0   
235617     6000.0                  13.0          0.0    1.0       6000.0   
235618    10000.0                  11.0          0.0    1.0      10000.0   
235619     8525.0                  83.0          1.0    

In [565]:
xy.reset_index(drop=True, inplace=True)
len1 = int(len(xy['loan_amnt'])/2)
data1 = xy['loan_status'].tolist()

for i in range(len1):
    if data1[i] == 0:
        xy.drop([i])
    if i%1000 == 0:
        print(i)

x = xy[['loan_amnt', 'mths_since_recent_bc', 'grade','funded_amnt','int_rate','installment','annual_inc']]
y = xy['loan_status']


0
1000
2000
3000
4000
5000
6000
7000
8000
9000
10000
11000
12000
13000
14000
15000
16000
17000
18000
19000
20000
21000
22000
23000
24000
25000
26000
27000
28000
29000
30000
31000
32000
33000
34000
35000
36000
37000
38000
39000
40000
41000
42000
43000
44000
45000
46000
47000
48000
49000
50000
51000
52000
53000
54000
55000
56000
57000
58000
59000
60000
61000
62000
63000
64000
65000
66000
67000
68000
69000
70000
71000
72000
73000
74000
75000
76000
77000
78000
79000
80000
81000
82000
83000
84000
85000
86000
87000
88000
89000
90000
91000
92000
93000
94000
95000
96000
97000
98000
99000
100000
101000
102000
103000
104000
105000
106000
107000
108000
109000
110000
111000
112000
113000
114000
115000


In [566]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size = 0.3,random_state = 15513)

In [567]:
min_max_scaler = preprocessing.MinMaxScaler()  
x_train_nor = min_max_scaler.fit_transform(x_train)
x_test_nor = min_max_scaler.transform(x_test)

c:\users\user\appdata\local\programs\python\python37\lib\site-packages\sklearn\preprocessing\data.py:323: DataConversionWarning: Data with input dtype float64, object were all converted to float64 by MinMaxScaler.
  return self.partial_fit(X, y)


In [568]:
for i in range(5,50):
    tree = DecisionTreeClassifier(criterion = 'entropy', random_state = 15513,max_depth = i)
    tree_clf = tree.fit(x_train_nor,y_train)
    y_test_predicted = tree_clf.predict(x_test_nor)
    y_train_predicted = tree_clf.predict(x_train_nor)
    accuracy = metrics.accuracy_score(y_test, y_test_predicted)
    #auc1 = metrics.confusion_matrix(y_train, y_train_predicted)
    auc = metrics.confusion_matrix(y_test, y_test_predicted)
    print(auc,accuracy,i)
"""
plt.plot(x_train_nor,y_train,'b.')
plt.plot(x_test_nor,y_test_predicted,'r.-')
plt.title('max_depth=3')
"""

[[56986     0]
 [12159     0]] 0.8241521440451226 5
[[56986     0]
 [12159     0]] 0.8241521440451226 6
[[56980     6]
 [12159     0]] 0.8240653698749005 7
[[56947    39]
 [12140    19]] 0.8238628968110493 8
[[56911    75]
 [12134    25]] 0.8234290259599393 9
[[56693   293]
 [12018   141]] 0.8219538650661653 10
[[56665   321]
 [12058   101]] 0.820970424470316 11
[[56398   588]
 [11968   191]] 0.8184105864487671 12
[[56202   784]
 [11912   247]] 0.8163858558102538 13
[[55718  1268]
 [11691   468]] 0.8125822546821896 14
[[55352  1634]
 [11614   545]] 0.8084026321498301 15
[[54879  2107]
 [11529   630]] 0.8027912358088076 16
[[54526  2460]
 [11435   724]] 0.799045484127558 17
[[53977  3009]
 [11263   896]] 0.7935931737652758 18
[[53432  3554]
 [11080  1079]] 0.7883577988285487 19
[[53074  3912]
 [10965  1194]] 0.7848434449345578 20
[[52427  4559]
 [10808  1351]] 0.7777568876997614 21
[[51815  5171]
 [10673  1486]] 0.7708583411671126 22
[[51295  5691]
 [10468  1691]] 0.7663026972304577 23


"\nplt.plot(x_train_nor,y_train,'b.')\nplt.plot(x_test_nor,y_test_predicted,'r.-')\nplt.title('max_depth=3')\n"

In [ ]:
"""
import os       
os.environ["PATH"] += os.pathsep + 'C:\Program Files (x86)\Graphviz2.38\bin'
import pydotplus
from IPython.display import Image
from sklearn.tree import export_graphviz
from PIL import Image as Im


dot_data = export_graphviz(tree_clf, out_file=None, feature_names=x.columns, filled=True, rounded=True, special_characters=True)
graph = pydotplus.graph_from_dot_data(dot_data)
graph.write_pdf('good.pdf')
"""

In [ ]:
a = 0
for i in y_test_predicted:
    a = i + a
print(a)


In [ ]:
y_test_predicted

In [ ]:
tree_clf

In [ ]:
accuracy

In [ ]:
df2

In [ ]:
importance = tree_clf.feature_importances_
features = x.columns
importance

In [ ]:
y_train

In [ ]:
x.head

In [ ]:
precision = metrics.precision_score(y_test, y_test_predicted)
precision

In [ ]:
xy.reindex()

In [ ]:
df2['grade'].plot.kde()
df2['loan_amnt'].plot.kde()

In [ ]:
fig = plt.figure()
for i in df2.columns:
    df2[i].plot.kde()